spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.94.104.224:3306/prp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

    #配置邮箱
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 742919609@qq.com
    password: dxrmojyvnjumbfbd
  redis:
    host: localhost
    port: 6379
    password: root

#    整合mybatis
mybatis:
  type-aliases-package: com.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080
